### PR TITLE
fix(reduce): better type and docs for `reduce` (#240)

### LINKED ISSUE #240: Better documentation and parameter name for `reduce`
# Suggestion

### Bad parameter name or generic name

In the jsdoc of `reduce`, variable name is really confusing since it's just `a` and `b`. After I inspect type signature, it's getting worse because of `(a: B, b: A) => B`. 

In tslib, they used following for `Array.prototype.reduce` .

```ts
reduce<U>(callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: T[]) => U, initialValue: U): U;
```

In [#MDN reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce), they use following description.

> Its return value becomes the value of the `accumulator` parameter on the next invocation of `callbackFn`.

For my suggestion, how about this? (in the manner of FxTS convention which has mathematical short things)

```ts
reduce<T, R>(f: (acc: R, value: T) => R, seed: R, ...)
```

### Requires more elaboration for docs of `reduce`

I think It's good to explain case of accumulator differ to value. I think it's pretty common in real life. Like adding following in the jsdoc of `reduce`.

```ts
// with accumulator
const data = [{ name: 'ppeeou', score: 25751 }, { name: 'shine1594': score: 74317 }, { name: 'jbl428', score: 366 }]
const scoreSum = reduce((acc, { score }) => acc + score, 0, data)
```

## 💻 Use Cases

More developers can understand the powerful features of `reduce`.

### PR DESCRIPTION
**Pull request by Phryxia**
At first I mentioned`R` but more describing `Acc` would be better.

- Change type `A`,`B` into `T`, `Acc` for `reduce`
- Give proper value name for `acc`, `value` instead of `a`, `b`
- Add example with explicit seed
- Add `@typeParam` for [tsdoc](https://tsdoc.org/pages/tags/typeparam/) support

Fixes #240

### CODE REVIEW

File: src/reduce.ts [hunk 1]
```diff
@@ -27,19 +31,49 @@ async function async<A, B>(
...
  *  reduce(sum),
  * ); // 26
+ * ```
+ *
+ * Currently, type with explicit seed form can't be inferred properly due to the limitation of typescript.
+ * But you can still use mostly with @ts-ignore flag. For more information please visit issue.
  *
+ * {@link https://github.com/marpple/FxTS/issues/239 | #related issue}
+ *
+ * Asynchronous things don't matter.
```
Comment (ppeeou) [inline src/reduce.ts:74]:
```suggestion
```

**Review by ppeeou — APPROVED** [review]
