### PR TITLE
fix: modify to use WeakMap properly in cache of memoize

### LINKED ISSUE #195: feature `memoize`
# Suggestion

## ⭐ Suggestion

https://github.com/marpple/FxTS/discussions/194

### PR DESCRIPTION
**Pull request by shine1594**
Fixes #195 
If the return type of the resolver function is object, then the cache should be assigned to a `WeakMap`. Currently only `Map` is used.

### CODE REVIEW

File: src/memoize.ts [hunk 1]
```diff
@@ -38,8 +38,12 @@ function memoize<
...
   const memoized = (...args: Parameters<typeof f>): ReturnType<F> => {
     const key = typeof resolver === "function" ? resolver(...args) : args[0];
-    const cache = memoized.cache;
-
+    const _self = memoized as any;
+    if (_self.cache === undefined) {
+      _self.cache =
+        key != null && typeof key === "object" ? new WeakMap() : new Map();
+    }
+    const { cache } = _self;
```
Comment (hg-pyun) [inline src/memoize.ts:46]: `weakMap` does not support the keys(), values(), entries() methods. Therefore, since you can access the map directly from the outside, it would be safer to have a separate interface to manipulate the cache.

Comment (shine1594) [reply src/memoize.ts:46]: So, you're suggesting to restrict the usage of WeakMap as a type for cache and just use Map instead, right?

Comment (hg-pyun) [reply src/memoize.ts:46]: No, how about providing an abstracted method?

Comment (shine1594) [reply src/memoize.ts:46]: Can you please write it in code and suggest it?

Comment (hg-pyun) [reply src/memoize.ts:46]: > Therefore, since you can access the map directly from the outside

I think the sentence above that I wrote before is wrong. I think I'm mistaken. I don't think it's a problem because _self is only used internally. 🙏

**Review by hg-pyun — APPROVED** [review]

**Review by ppeeou — APPROVED** [review]
👍

**Review by ppeeou — APPROVED** [review]
👍
